import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import AuthProvider from "./(components)/common/AuthProvider";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Donyati Wizard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  );
}
